name: typeid
description: A spec conformant implementation of the TypeID standard. TypeIDs are K-sortable, globally unique identifier inspired by Stripe IDs
version: 1.0.0
repository: https://github.com/TBD54566975/typeid-dart

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  uuid: ^4.3.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
